env:
  browser: true
  es2021: true
  node: true
extends:
  - airbnb-base
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: ['./tsconfig.json', './example/tsconfig.json']
plugins:
  - '@typescript-eslint'
rules: {
  '@typescript-eslint/strict-boolean-expressions': 0,
  'import/no-extraneous-dependencies': 0,
  'import/no-unresolved': 0,
  'import/extensions': 0
}
